### ISSUE TITLE
Clean up source code

### ISSUE THREAD

**Issue by lahmatiy** [Mavrin/karma-yatra#1]
### Adapter.js

Those should work (`core.runner` instead of `./x.js` and `core.test`)

``` js
            var runner = basis.require('core.runner');
            var rootTest = basis.require('core.test').create(basis.require('./base/test/index.js'));
```

Better error output:

``` js
            runner.on('report', function (report) {
                tc.result({
                    id: '', // ?
                    description: report.name,
                    suite: [report.path.slice(1).join(' / ') + ' /'],
                    success: report.success,
                    skipped: report.skipped,
                    time: report.time,
                    log: report.errors
                      ? report.errors.map(function(er){
                          return er.type + ' at line ' + er.line +
                            '\n  Expected: ' + er.expected +
                            '\n  Actual:   ' + er.actual
                        })
                      : report.exception
                        ? ['Exception:' + report.exception]
                        : []
                });
            });

```

**Comment by Mavrin** [comment]
В целом я хочу сделать, чтобы раннер брал последнюю стабильную не собранную
версию и подключал средствами basisjs(думаю это не сильно скажется на
производительности), причина этого:сейчас я не могу напрямую использовать
билд, так ломаются пути к worker и мне приходится руками фиксить пути. Но
пока не получилось заставить karma server загружать, но не инклудить файлы
в страницу. Хотя вроде делаю все согласно документации.
Я кстати думал, что референсы на исходные файлы теряются, оказывается, что
нет.

ср, 28 янв. 2015, 18:18, Roman Dvornov notifications@github.com:

**Comment by lahmatiy** [comment]
> сейчас я не могу напрямую использовать билд, так ломаются пути к worker и мне приходится руками фиксит

У этой проблемы должно быть решение. Я посмотрю как это побороть – до этого не знал о проблеме.

> Я кстати думал, что референсы на исходные файлы теряются, оказывается, что
> нет.

Настоящие пути теряются, но информация о "нейспейсах" сохраняется (в сборку зашивается своего рода карта соотвествий).

**Comment by Mavrin** [comment]
В целом с worker у меня сейчас две проблемы. 
Первая мне пришлось добавить такую строку в сам воркер https://github.com/Mavrin/karma-basisjs-test-runner/blob/master/lib/res/E6P4bhb55znfCzAa1Pbfbw.js#L1. Это связанно с работой кармы сервера, я думаю это должно как-то решаться,но пока почему-то не вышло, собираюсь поддебажить сами потроха кармы. По идеи worker необходимо загружать createPattern2, что бы файл оказался на сервере, но включался в страницу, но тут что-то происходит странное и оно не работает, пока не смог одуплить. 

``` js
var createPattern = function(path) {
  return {pattern: path, included: true, served: true, watched: false};
};
var createPattern2 = function(path) {
    return {pattern: path, included: false};
};
```

Если не видел, вот дока где они описывают как все работает. 
https://raw.githubusercontent.com/karma-runner/karma/master/thesis.pdf
В целом я думал как побороть пути, сделать путь к папке res через config.
https://raw.githubusercontent.com/karma-runner/karma/master/thesis.pdf
Вроде этого

``` js
var pathToWorker = config.pathToWorker || './res/';
var worker = new Worker(pathToWorker + "E6P4bhb55znfCzAa1Pbfbw.js");
```
