### ISSUE TITLE
Rename and publish in npm

### ISSUE THREAD

**Issue by lahmatiy** [Mavrin/karma-yatra#3]
Please, do the follow:
- rename repo to `karma-yatra`
- add version to `package.json` (I suppose `1.0.0` will be great)
- publish in npm (`npm publish` in repo folder)

Thanks!

**Comment by Mavrin** [comment]
I think will be better move this repo to basis/karma-yatra? What do you mean about it?
But before publish 1.0.0 , i should fix karma with `singleRun:false`. Now karma-yatra doesn't work with this flag. And add unit test.

**Comment by lahmatiy** [comment]
It's would be great. But you should rename it first. Than transfer the ownership to `basisjs`.
I don't know about problem with `singleRun:false`. In this mode your should press `debug` button in opened browser just the case. Or what do you mean?

**Comment by Mavrin** [comment]
All works good. Just i run test with flag 'autoWatch: false'. 'Press to debug' isn't necessary. If you run karma with autoWatch is enabled, Then on change test file or your code, which describe in files section of karma config, karma automatically re run all tests and print result in console.
